import "./globals.css";

import { Inter } from "next/font/google";

import HomeHeader from "@/components/home-header";
import HomeServer from "@/components/home-server";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`}>
        <div className="relative flex h-screen flex-col overflow-hidden">
          {/* Header */}
          <HomeHeader />

          <HomeServer>
            {/* Children */}
            {children}
          </HomeServer>
        </div>
      </body>
    </html>
  );
}
